config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'homes#top'

  resources :books do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :movies do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
  	member do
  		get :following, :followers, :user_posts
  	end
  	resource :favorites, only: [:show]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index] do
    collection do
      delete :destroy_all
    end
  end

  get 'search' => 'searches#search'

end

app/models/block.rb
class Block < ApplicationRecord
	belongs_to :blocker, class_name: "User"
	belongs_to :blocked, class_name: "User"
end

app/models/book.rb
class Book < Post
	validates :author, presence: true
end

app/models/book_category.rb
class BookCategory < Category
end

app/models/book_genre.rb
class BookGenre < Genre
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :post
	has_many :genre_relations
	has_many :genres, through: :genre_relations
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :genre_relations
	has_many :categories, through: :genre_relations
end

app/models/genre_relation.rb
class GenreRelation < ApplicationRecord
	belongs_to :categories
	belongs_to :genres
end

app/models/movie.rb
class Movie < Post
end

app/models/movie_genre.rb
class MovieGenre < Genre
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :post, optional: true
	belongs_to :comment, optional: true

	belongs_to :visiter, class_name: "User", foreign_key: "visiter_id", optional: true
	belongs_to :visited, class_name: "User", foreign_key: "visited_id", optional: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :notifications, dependent: :destroy

	validates :title, presence: true, length: {maximum: 200}
	validates :subject, presence: true, length: {maximum: 50}
	validates :body, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search(word)
		Post.where("title LIKE? OR author LIKE?" ,"%#{word}%", "%#{word}%")
	end

	def create_notification_by!(current_user)
		# すでにお気に入りされているか検索
		temp = Notification.where(["visiter_id = ? and visited_id = ? and post_id = ? and action = ?", current_user.id, user_id, id, 'favorite'])
		if temp.blank?
			notification = current_user.active_notifications.new(
				post_id: id,
				visited_id: user_id,
				action: "favorite"
				)
			# 自分の投稿に対するお気に入りの場合は、通知済みにする
			if notification.visiter_id == notification.visited_id
				notification.checked = true
			end
			notification.save if notification.valid?
		end
	end

	def create_notification_comment!(current_user, comment_id)
		# 自分以外にコメントしている人をすべて取得し、全員に通知を送る
		temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
		temp_ids.each do |temp_id|
			save_notification_comment!(current_user, comment_id, temp_id['user_id'])
		end
		# まだ誰もコメントしていない場合、投稿者に通知を送る
		save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
	end

	def save_notification_comment!(current_user, comment_id, visited_id)
		# コメントは複数回する場合があるため、1つの投稿に複数回通知する
		notification = current_user.active_notifications.new(
			post_id: id,
			comment_id: comment_id,
			visited_id: visited_id,
			action: 'comment'
			)
		# 自分の投稿に対するコメントの場合は通知済みとする
		if notification.visiter_id == notification.visited_id
			notification.checked = true
		end
		notification.save if notification.valid?
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
            foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship",
            foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :active_notifications, class_name: "Notification",
            foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification",
            foreign_key: "visited_id", dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2, maximum: 20}

  def self.search(word)
    User.where("name LIKE?", "%#{word}%")
  end


  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
        )
      notification.save if notification.valid?
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def show
		@favorites = Favorite.where(user_id: params[:user_id]).reverse_order.page(params[:page]).per(10)
	end

	def create
		if params[:book_id]
			@book = Book.find(params[:book_id])
			favorite = current_user.favorites.new(post_id: @book.id)
			favorite.save
			post = Post.find(params[:book_id])
			post.create_notification_by!(current_user)
			@check = "book"
		else
			@movie = Movie.find(params[:movie_id])
			favorite = current_user.favorites.new(post_id: @movie.id)
			favorite.save
			post = Post.find(params[:movie_id])
			post.create_notification_by!(current_user)
			@check = "movie"
		end
	end

	def destroy
		if params[:book_id]
			@book = Book.find(params[:book_id])
			favorite = current_user.favorites.find_by(post_id: @book.id)
			favorite.destroy
			@check = "book"
		else
			@movie = Movie.find(params[:movie_id])
			favorite = current_user.favorites.find_by(post_id: @movie.id)
			favorite.destroy
			@check = "movie"
		end
		#favorites/_book(movie)_favorite(投稿の詳細ページ)からは"show"
		#favorites/show(マイページのお気入り一覧)からは"mypage"のパラメーターを受け取り、結果を分岐。
		case params[:request_from]
		when 'show'
			render :destroy
		when 'mypage'
			redirect_back(fallback_location: root_path)
		end
	end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_book_favorite.html.erb
<% if user_signed_in? %>
	<% if book.favorited_by?(current_user) %>
		<%= link_to book_favorites_path(book, request_from: 'show'), method: :delete, remote: true do %>
		<i class="glyphicon glyphicon-star" aria-hidden="true"></i>
		<%= book.favorites.count %> 件のお気に入り
		<% end %>
	<% else %>
		<%= link_to book_favorites_path(book), method: :post, remote: true do %>
		<i class="glyphicon glyphicon-star-empty" aria-hidden="true"></i>
		<%= book.favorites.count %> 件のお気に入り
		<% end %>
	<% end %>
<% else %>
	<p><i class="glyphicon glyphicon-star" aria-hidden="true"></i><%= book.favorites.count %>件のお気に入り</p>
<% end %>

app/views/favorites/_movie_favorite.html.erb
<% if user_signed_in? %>
	<% if movie.favorited_by?(current_user) %>
		<%= link_to movie_favorites_path(movie, request_from: 'show'), method: :delete, remote: true do %>
		<i class="glyphicon glyphicon-star" aria-hidden="true"></i>
		<%= movie.favorites.count %> 件のお気に入り
		<% end %>
	<% else %>
		<%= link_to movie_favorites_path(movie), method: :post, remote: true do %>
		<i class="glyphicon glyphicon-star-empty" aria-hidden="true"></i>
		<%= movie.favorites.count %> 件のお気に入り
		<% end %>
	<% end %>
<% else %>
	<p><i class="glyphicon glyphicon-star" aria-hidden="true"></i><%= movie.favorites.count %>件のお気に入り</p>
<% end %>

app/views/favorites/create.js.erb
<% if @check == "book" %>
	$('#Favorite_<%= @book.id %>').html("<%= j(render partial: 'favorites/book_favorite', locals: {book: @book}) %>");
<% elsif @check == "movie" %>
	$('#Favorite_<%= @movie.id %>').html("<%= j(render partial: 'favorites/movie_favorite', locals: {movie: @movie}) %>");
<% end %>

app/views/favorites/destroy.js.erb
<% if @check == "book" %>
	$('#Favorite_<%= @book.id %>').html("<%= j(render partial: 'favorites/book_favorite', locals: {book: @book}) %>");
<% elsif @check == "movie" %>
	$('#Favorite_<%= @movie.id %>').html("<%= j(render partial: 'favorites/movie_favorite', locals: {movie: @movie}) %>");
<% end %>

app/views/favorites/show.html.erb
<h2>お気に入り一覧</h2>

<div>
	<table class="table">
		<thead>
			<tr>
				<th>カテゴリー</th>
				<th>タイトル</th>
				<th>件名</th>
				<th>投稿者</th>
				<th>お気に入り解除</th>
			</tr>
		</thead>
		<% @favorites.each do |favorite| %>
		<tbody>
			<tr>
				<% if favorite.post.type == "Book" %>
				<td><span class="label label-primary"><%=favorite.post.category.category %></span></td>
				<td><%= link_to "#{favorite.post.title}", book_path(favorite.post.id) %></td>
				<td><%= link_to "#{favorite.post.subject}", book_path(favorite.post.id) %></td>
				<td><%= link_to "#{favorite.post.user.name}", user_path(favorite.post.user.id) %></td>
				<td><%= link_to book_favorites_path(favorite.post.id, request_from: 'mypage'), method: :delete do %>
					<i class="glyphicon glyphicon-star" aria-hidden="true"></i></div>
					<% end %>
				</td>
				<% else %>
				<td><span class="label label-primary"><%=favorite.post.category.category %></span></td>
				<td><%= link_to "#{favorite.post.title}", movie_path(favorite.post.id) %></td>
				<td><%= link_to "#{favorite.post.subject}", movie_path(favorite.post.id) %></td>
				<td><%= link_to "#{favorite.post.user.name}", user_path(favorite.post.user.id) %></td>
				<td><%= link_to movie_favorites_path(favorite.post.id, request_from: 'mypage'), method: :delete do %>
					<i class="glyphicon glyphicon-star" aria-hidden="true"></i>
					<% end %>
				</td>
				<% end %>
			</tr>
		</tbody>
		<% end %>
	</table>
</div>

<%= paginate @favorites %>