config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'homes#top'

  resources :books do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :movies do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
  	member do
  		get :following, :followers, :user_posts
  	end
  	resource :favorites, only: [:show]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index] do
    collection do
      delete :destroy_all
    end
  end

  get 'search' => 'searches#search'

end

app/models/block.rb
class Block < ApplicationRecord
	belongs_to :blocker, class_name: "User"
	belongs_to :blocked, class_name: "User"
end

app/models/book.rb
class Book < Post
	validates :author, presence: true
end

app/models/book_category.rb
class BookCategory < Category
end

app/models/book_genre.rb
class BookGenre < Genre
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :post
	has_many :genre_relations
	has_many :genres, through: :genre_relations
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :genre_relations
	has_many :categories, through: :genre_relations
end

app/models/genre_relation.rb
class GenreRelation < ApplicationRecord
	belongs_to :categories
	belongs_to :genres
end

app/models/movie.rb
class Movie < Post
end

app/models/movie_category.rb
class MovieCategory < Category
end

app/models/movie_genre.rb
class MovieGenre < Genre
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :post, optional: true
	belongs_to :comment, optional: true

	belongs_to :visiter, class_name: "User", foreign_key: "visiter_id", optional: true
	belongs_to :visited, class_name: "User", foreign_key: "visited_id", optional: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :notifications, dependent: :destroy

	validates :title, presence: true, length: {maximum: 200}
	validates :subject, presence: true, length: {maximum: 50}
	validates :body, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search(word)
		Post.where("title LIKE? OR author LIKE?" ,"%#{word}%", "%#{word}%")
	end

	def create_notification_by!(current_user)
		# すでにお気に入りされているか検索
		temp = Notification.where(["visiter_id = ? and visited_id = ? and post_id = ? and action = ?", current_user.id, user_id, id, 'favorite'])
		if temp.blank?
			notification = current_user.active_notifications.new(
				post_id: id,
				visited_id: user_id,
				action: "favorite"
				)
			# 自分の投稿に対するお気に入りの場合は、通知済みにする
			if notification.visiter_id == notification.visited_id
				notification.checked = true
			end
			notification.save if notification.valid?
		end
	end

	def create_notification_comment!(current_user, comment_id)
		# 自分以外にコメントしている人をすべて取得し、全員に通知を送る
		temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
		temp_ids.each do |temp_id|
			save_notification_comment!(current_user, comment_id, temp_id['user_id'])
		end
		# まだ誰もコメントしていない場合、投稿者に通知を送る
		save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
	end

	def save_notification_comment!(current_user, comment_id, visited_id)
		# コメントは複数回する場合があるため、1つの投稿に複数回通知する
		notification = current_user.active_notifications.new(
			post_id: id,
			comment_id: comment_id,
			visited_id: visited_id,
			action: 'comment'
			)
		# 自分の投稿に対するコメントの場合は通知済みとする
		if notification.visiter_id == notification.visited_id
			notification.checked = true
		end
		notification.save if notification.valid?
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
            foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship",
            foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :active_notifications, class_name: "Notification",
            foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification",
            foreign_key: "visited_id", dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2, maximum: 20}

  def self.search(word)
    User.where("name LIKE?", "%#{word}%")
  end


  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
        )
      notification.save if notification.valid?
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!, only:[:edit, :update]
	before_action :correct_user, only:[:edit, :update]

  def index
  end

  def show
  	@user = User.find(params[:id])
  	@books = @user.posts
    # if @user != nil && @user.profile_image_id != nil
    #   @image_url = "https://yourfavorites-resize.s3-ap-northeast-1.amazonaws.com/store/" + @user.profile_image_id + "-thumbnail."
    # else
    #   @image_url = "/assets/no_image-c7305210e2d30bf8f19461ca05a151bba6413a44a35124f673246160efefdc5e.jpg"
    # end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		flash[:notice] = "ユーザーの情報を更新しました"
  		redirect_to user_path(@user.id)
  	else
  		render "edit"
  	end
  end

  def following
    @title = "フォロー"
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page]).reverse_order
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).reverse_order
    render 'show_follow'
  end

  def user_posts
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])

    @sort = params[:sort]
    if @sort == 'new'
      @posts = @posts.page(params[:page]).order(created_at: :DESC)
    elsif @sort == 'old'
      @posts = @posts.page(params[:page]).order(created_at: :ASC)
    elsif @sort == 'favorite'
      @posts = @posts.left_joins(:favorites).group(:id).order(Arel.sql('COUNT(favorites.id)')).reverse_order.page(params[:page])
    elsif @sort == 'high_rating'
      @posts = @posts.page(params[:page]).order(rating: :DESC)
    elsif @sort == 'low_rating'
      @posts = @posts.page(params[:page]).order(rating: :ASC)
    else
     @posts = @posts.page(params[:page]).reverse_order
    end
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :introduction, :profile_image)
  	end

  	def correct_user
  		user = User.find(params[:id])
  		if current_user != user
  			redirect_to user_path(current_user)
  		end
  	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<% if user_signed_in? %>
	<% unless user == current_user %>
		<% if current_user.following?(user) %>
			<!-- フォロー解除するフォーム -->
			<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
	             html: { method: :delete }, data: { remote: true }) do |f| %>
			 <%= f.submit "フォロー解除", class: "btn btn-primary" %>
			<% end %>
		<% else %>
			<!-- ユーザーをフォローするフォーム -->
			<%= form_for(current_user.active_relationships.build, data: { remote: true }) do |f| %>
			  <%= hidden_field_tag :followed_id, user.id %>
			  <%= f.submit "フォロー", class: "btn btn-primary" %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/users/edit.html.erb
<h2>登録情報変更</h2>

<%= form_for @user do |f| %>

<%= render 'shared/error_messages', model: f.object %>

	<div class="form-group">
		<%= f.label :name, 'ユーザー名' %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :image, 'プロフィール画像' %>
		<%= f.attachment_field :profile_image %>
	</div>

	<div class="form-group">
		<%= f.label :introduction, '自己紹介' %>
		<%= f.text_area :introduction, class: 'form-control', rows: 5 %>
	</div>

	<div>
		<%= f.submit "更新", class: 'btn btn-primary' %>
	</div>
<% end %>

app/views/users/show.html.erb
<h2><b><%= @user.name %></b> さんのページ</h2>
<div class="mypage_body">

<div class="col-md-3">
	<div class="profile_icon">
		<%= attachment_image_tag @user, :profile_image, :fill, 150, 150, format: 'jpeg',fallback: "no_image.jpg",size: '150x150', class: "img-circle" %>
	</div>

	<%#= image_tag @image_url, class: "img-circle" %>

	<% if user_signed_in? %>
		<% if @user.id == current_user.id %>
			<div class="mypage_btn">
				<%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-primary" %>
			</div>
		<% end %>
	<% end %>

	<div class="follow_form_<%= @user.id %>">
		<%= render 'follow_form', user: @user %>
	</div>
</div>

<div class="col-md-5">
	<div class="introduction-header text-center">
		<p>自己紹介文</p>
	</div>
	<div class="introduction">
		<p><%=  simple_format(@user.introduction) %></p>
	</div>
</div>

<div class="col-md-4">
	<% if user_signed_in? %>
		<% if @user.id == current_user.id %>
			<div class="post_form text-center">
				<h4>感想を投稿する</h4>
				<div class="mypage_btn">
					<%= link_to "本の感想を投稿", new_book_path, class: "btn btn-primary" %>
				</div>
				<div class="mypage_btn">
					<%= link_to "映像作品の感想を投稿", new_movie_path, class: "btn btn-primary" %>
				</div>
			</div>
		<% end %>
	<% end %>
</div>



<div class="col-md-12">
	<div class="under_menu">
		<ul>
			<div class="col-xs-3">
				<li><%= link_to following_user_path(@user) do %>
						<i class="fa fa-group"></i><br>
						<span class="follow_count_<%= @user.id %>"> <%= @user.following.count %></span> フォロー
					<% end %>
				</li>
			</div>
			<div class="col-xs-3">
				<li><%= link_to followers_user_path(@user) do %>
						<i class="fa fa-users"></i><br>
						<span class="follower_count_<%= @user.id %>"> <%= @user.followers.count %></span> フォロワー
					<% end %>
				</li>
			</div>
			<div class="col-xs-3">
				<li><%= link_to user_favorites_path(@user) do %>
						<i class="glyphicon glyphicon-star"></i><br>お気に入り
					<% end %>
				</li>
			</div>
			<div class="col-xs-3">
				<li><%= link_to user_posts_user_path(@user) do %>
						<i class="glyphicon glyphicon-pencil"></i><br>投稿一覧
					<% end %>
				</li>
			</div>
		</ul>
	</div>
</div>

</div>

app/views/users/show_follow.html.erb
<h1><%= @title %></h1>
	<table class="table">

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" ,size:'40x40' %></td>
				<td><%= link_to "#{user.name}", user_path(user.id) %></td>
				<td>
					<%= link_to "#{user.following.count}", following_user_path(user), class: "follow_count_#{user.id}" %>フォロー
				</td>
				<td>
					<%= link_to "#{user.followers.count}", followers_user_path(user), class: "follower_count_#{user.id}" %>フォロワー
				</td>
				<td>
					<% unless user == current_user %>
						<div class="follow_form_<%= user.id %>">
							<%= render 'users/follow_form', user: user %>
						</div>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<%= paginate @users %>

app/views/users/user_posts.html.erb
<div class="pull-right">
  <%= form_with url: user_posts_user_path, method: :get, local: true do |f| %>
   <%= f.select :sort, [ ['並び替え', ''],
   						 ['投稿が新しい順', 'new'],
   						 ['投稿が古い順','old'],
   						 ['お気に入りが多い順', 'favorite'],
   						 ['評価が高い順', 'high_rating'],
   						 ['評価が低い順', 'low_rating'],
   					   ],
   					   {},class: "form-control", style: "width: 200px;",
   					   onchange: "$(this).closest('form').submit() " %>
  <% end %>
 </div>

<h3><%= @user.name %>さんの投稿一覧</h3>

<table class="table">
	<thead>
		<tr>
			<th>投稿者</th>
			<th>カテゴリー</th>
			<th>作品名</th>
			<th>件名</th>
			<th>投稿日時</th>
			<th>お気に入り数</th>

		</tr>
	</thead>
	<% @posts.each do |post| %>
	<tbody>
		<tr>
			<td><%= link_to user_path(post.user_id) do %>
				<%= attachment_image_tag post.user, :profile_image, :fill, 40, 40, format: 'jpeg',fallback:"no_image.jpg",size:'40x40' %><br>
				<%= post.user.name %>
				<% end %>
			</td>
			<td><span class="label label-primary"><%= post.category.category %></span></td>
			<td><%= post.title %></td>
			<td><%= post.subject %></td>
			<td><%= post.created_at.to_s(:datetime_jp) %></td>
			<td><%= post.favorites.count %></td>
			<td>
				<% if post.type == "Book"%>
					<%= link_to "詳細", book_path(post) %>
				<% else %>
					<%= link_to "詳細", movie_path(post) %>
				<% end %>
			</td>

		</tr>
	</tbody>
	<% end %>
</table>

<%= paginate @posts %>