config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'homes#top'

  resources :books do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :movies do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
  	member do
  		get :following, :followers, :user_posts
  	end
  	resource :favorites, only: [:show]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index] do
    collection do
      delete :destroy_all
    end
  end

  get 'search' => 'searches#search'

end

app/models/block.rb
class Block < ApplicationRecord
	belongs_to :blocker, class_name: "User"
	belongs_to :blocked, class_name: "User"
end

app/models/book.rb
class Book < Post
	validates :author, presence: true
end

app/models/book_category.rb
class BookCategory < Category
end

app/models/book_genre.rb
class BookGenre < Genre
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :post
	has_many :genre_relations
	has_many :genres, through: :genre_relations
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :genre_relations
	has_many :categories, through: :genre_relations
end

app/models/movie.rb
class Movie < Post
end

app/models/movie_genre.rb
class MovieGenre < Genre
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :post, optional: true
	belongs_to :comment, optional: true

	belongs_to :visiter, class_name: "User", foreign_key: "visiter_id", optional: true
	belongs_to :visited, class_name: "User", foreign_key: "visited_id", optional: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :notifications, dependent: :destroy

	validates :title, presence: true, length: {maximum: 200}
	validates :subject, presence: true, length: {maximum: 50}
	validates :body, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search(word)
		Post.where("title LIKE? OR author LIKE?" ,"%#{word}%", "%#{word}%")
	end

	def create_notification_by!(current_user)
		# すでにお気に入りされているか検索
		temp = Notification.where(["visiter_id = ? and visited_id = ? and post_id = ? and action = ?", current_user.id, user_id, id, 'favorite'])
		if temp.blank?
			notification = current_user.active_notifications.new(
				post_id: id,
				visited_id: user_id,
				action: "favorite"
				)
			# 自分の投稿に対するお気に入りの場合は、通知済みにする
			if notification.visiter_id == notification.visited_id
				notification.checked = true
			end
			notification.save if notification.valid?
		end
	end

	def create_notification_comment!(current_user, comment_id)
		# 自分以外にコメントしている人をすべて取得し、全員に通知を送る
		temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
		temp_ids.each do |temp_id|
			save_notification_comment!(current_user, comment_id, temp_id['user_id'])
		end
		# まだ誰もコメントしていない場合、投稿者に通知を送る
		save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
	end

	def save_notification_comment!(current_user, comment_id, visited_id)
		# コメントは複数回する場合があるため、1つの投稿に複数回通知する
		notification = current_user.active_notifications.new(
			post_id: id,
			comment_id: comment_id,
			visited_id: visited_id,
			action: 'comment'
			)
		# 自分の投稿に対するコメントの場合は通知済みとする
		if notification.visiter_id == notification.visited_id
			notification.checked = true
		end
		notification.save if notification.valid?
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
            foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship",
            foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :active_notifications, class_name: "Notification",
            foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification",
            foreign_key: "visited_id", dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2, maximum: 20}

  def self.search(word)
    User.where("name LIKE?", "%#{word}%")
  end


  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
        )
      notification.save if notification.valid?
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_search_form.html.erb
<!-- モーダル・ダイアログ -->
<div class="modal fade" id="SearchModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span>×</span></button>
        <h4 class="modal-title">検索フォーム</h4>
      </div>
      <div class="modal-body">
        <div class="search_form form-inline" >
          <%= form_tag(search_path, method: :get) do %>
            <%= select_tag 'select_model' ,options_for_select([['ユーザー', 'user'],['投稿','post']]),class: "form-control", style: "width: 100px;" %>
            <%= text_field_tag (:word), "", class: "form-control",style: "width: 50%" %>
            <%= submit_tag "検索", class: "btn btn-default" %>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Favorites</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Rowdies&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="wrapper">
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="conteiner">
        <nav class="nav navbar-nav navbar-left">
          <span id="logo">Your Favorites</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to user_path(current_user) do %><i class="glyphicon glyphicon-user"></i>&emsp;マイページ<% end %></li>
            <li>
              <%= link_to notifications_path do %><i class="glyphicon glyphicon-bell"></i>&emsp;通知<% end %>
              <% if unchecked_notifications.any? %>
                <i class="fa fa-circle" style="color: gold;"></i>
              <% end %>
            </li>
            <li>
              <!-- 検索モーダル・ダイアログ呼び出し部 -->
              <a href="#" data-toggle="modal" data-target="#SearchModal">
                <i class="glyphicon glyphicon-search">&emsp;検索</i>
              </a>
            </li>
            <li><%= link_to books_path do %><i class="glyphicon glyphicon-book"></i>&emsp;本<% end %></li>
            <li><%= link_to movies_path do %><i class="glyphicon glyphicon-film"></i>&emsp;映像作品<% end %></li>
            <li><%= link_to destroy_user_session_path, method: :delete do %><i class="glyphicon glyphicon-log-out"></i>&emsp;ログアウト<% end %></li>
          <% else %>
            <li><%= link_to root_path do %><i class="glyphicon glyphicon-home home"></i>&emsp;Home<% end %></li>
            <li><%= link_to new_user_registration_path do %><i class="glyphicon glyphicon-edit"></i>&emsp;新規登録</li><% end %>
            <li><%= link_to new_user_session_path do %><i class="glyphicon glyphicon-log-in"></i>&emsp;ログイン<% end %></li>
            <li><%= link_to books_path do %><i class="glyphicon glyphicon-book"></i>&emsp;本<% end %></li>
            <li><%= link_to movies_path do %><i class="glyphicon glyphicon-film"></i>&emsp;映像作品<% end %></li>
          <% end %>
          </ul>
        </nav>
      </div>
    </header>

<!-- 検索モーダル・ダイアログ部 -->
<%= render "layouts/search_form" %>

<!-- 画面サイズに合わせてヘッダーの高さを変化させる -->
<script>
$(window).on('load resize', function(){
    // navbarの高さを取得する
    var height = $('.navbar').height();
    // bodyのpaddingにnavbarの高さを設定する
    $('body').css('padding-top',height + 20);
});
</script>

<% if flash[:notice] %>
  <div class="alert alert-success text-center" role="alert">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert]%>
  <div class="alert alert-danger text-center" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

  <div class="main">
      <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </div>


    <footer>
      <div>
        <p> &copy; YourFavorites</p>
      </div>
    </footer>

  </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
	<div class="alert alert-danger">
		<ul>
			<% model.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>